//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaeedClinick.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinickEntities1 : DbContext
    {
        public clinickEntities1()
            : base("name=clinickEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LK_Labs> LK_Labs { get; set; }
        public virtual DbSet<LK_Treatment> LK_Treatment { get; set; }
        public virtual DbSet<LK_US> LK_US { get; set; }
        //public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<PatientData> PatientDatas { get; set; }
        public virtual DbSet<VisitLab> VisitLabs { get; set; }
        public virtual DbSet<VisitTreatment> VisitTreatments { get; set; }
        public virtual DbSet<VisitU> VisitUS { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
    }
}
