//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaeedClinick.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientData()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string FileNum { get; set; }
        public string TelephoneNum { get; set; }
        public string Address { get; set; }
        public string Marrid { get; set; }
        public string RH { get; set; }
        public string LMB { get; set; }
        public string EDD { get; set; }
        public string GPA { get; set; }
        public string Others { get; set; }
        public string MedicalHistory { get; set; }
        public string SurgicalHistory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
