//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaeedClinick.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class VisitU
    {
        public int Id { get; set; }
        [ForeignKey("LK_US")]
        public int USId { get; set; }
        [ForeignKey("Visit")]
        public int VisitId { get; set; }
    
        public virtual LK_US LK_US { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
